{% set name = "austin-python" %}
{% set version = "1.2.2" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/austin-python-{{ version }}.tar.gz
  sha256: 817b899b308d1235ec7426db94fa6f721960909c6b03d2d1ff0bb3ac01b01ef7

build:
  number: 1
  skip: true  # [win]
  entry_points:
    - austin-compress = austin.format.compress:main
    - austin-diff = austin.tools.diff:main
    - austin2pprof = austin.format.pprof.__main__:main
    - austin2speedscope = austin.format.speedscope:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - sysroot_linux-64 2.17  # [linux64]
  host:
    - pip
    - poetry
    - python
  run:
    - dataclasses
    - protobuf >=3.12.2
    - psutil >=5.7.0
    - python
    - toml >=0.10.2
    - austin

test:
  imports:
    - austin
  commands:
    - pip check
    - austin-compress --help
    - austin-diff --help
    - austin2pprof --help
    - austin2speedscope --help
  requires:
    - pip

about:
  home: https://github.com/P403n1x87/austin-python
  summary: Python wrapper for Austin, the frame stack sampler for CPython
  license: GPL-3.0-or-later
  license_file: LICENSE.md

extra:
  recipe-maintainers:
    - siboehm
