{% set name = "austin-python" %}
{% set version = "2.1.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 58faeed586a74bf6151a4c85f07993980809fc1f595ab235cd7500f0b9ae60ab

build:
  number: 0
  skip: true  # [win]
  entry_points:
    - austin-compress = austin.format.compress:main
    - austin-diff = austin.tools.diff:main
    - austin2pprof = austin.format.pprof.__main__:main
    - austin2speedscope = austin.format.speedscope:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
  host:
    - pip
    - python
    - hatchling
    - hatch-vcs
  run:
    - protobuf <5  # FIXME: this should be '~=3.12.2'.
    - psutil >=5.7.0
    - python
    - toml <1 # TODO: hardpinned upstream to ~=0.10.2
    - austin

test:
  imports:
    - austin
  commands:
    # - pip check  # disabled due to incorrect protobuf version above.
    - austin-compress --help
    - austin-diff --help
    - austin2pprof --help
    - austin2speedscope --help
  requires:
    - pip

about:
  home: https://github.com/P403n1x87/austin-python
  summary: Python wrapper for Austin, the frame stack sampler for CPython
  license: GPL-3.0-or-later
  license_file: LICENSE.md
  doc_url: https://austin-python.readthedocs.io/en/latest/
  dev_url: https://github.com/P403n1x87/austin-python

extra:
  recipe-maintainers:
    - siboehm
    - matthiasdiener
